import './globals.css';
import type { Metadata } from 'next';
import Footer from './common/Footer/Footer';
import Nav from './common/Nav/Nav';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
